# CMake generated Testfile for 
# Source directory: C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test
# Build directory: E:/PROG/Libraries/SDL2/SDL2-2.30.5/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testautomation "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testautomation.exe")
set_tests_properties(testautomation PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "120" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testatomic "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testatomic.exe")
set_tests_properties(testatomic PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testerror "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testerror.exe")
set_tests_properties(testerror PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testthread "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testthread.exe")
set_tests_properties(testthread PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "40" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testlocale "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testlocale.exe")
set_tests_properties(testlocale PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testplatform "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testplatform.exe")
set_tests_properties(testplatform PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testpower "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testpower.exe")
set_tests_properties(testpower PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testfilesystem "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testfilesystem.exe")
set_tests_properties(testfilesystem PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testtimer "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testtimer.exe")
set_tests_properties(testtimer PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "60" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testver "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testver.exe")
set_tests_properties(testver PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testqsort "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testqsort.exe")
set_tests_properties(testqsort PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testaudioinfo "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testaudioinfo.exe")
set_tests_properties(testaudioinfo PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testsurround "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testsurround.exe")
set_tests_properties(testsurround PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testkeys "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testkeys.exe")
set_tests_properties(testkeys PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testbounds "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testbounds.exe")
set_tests_properties(testbounds PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
add_test(testdisplayinfo "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test/testdisplayinfo.exe")
set_tests_properties(testdisplayinfo PROPERTIES  ENVIRONMENT "SDL_AUDIODRIVER=dummy;SDL_VIDEODRIVER=dummy" TIMEOUT "10" WORKING_DIRECTORY "E:/PROG/Libraries/SDL2/SDL2-2.30.5/test" _BACKTRACE_TRIPLES "C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;473;add_test;C:/Users/Sergey/Desktop/raw_library/SDL2-2.30.5/test/CMakeLists.txt;0;")
